apiVersion: apps/v1
kind: Deployment
metadata:
  name: multool
  namespace: netology
  labels:
    app: multool
spec:
  selector:
    matchLabels:
      app: multool
  replicas: 1
  template:
    metadata:
      labels:
        app: multool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env: 
          - name: HTTP_PORT
            value: "7880"
        volumeMounts:
        - name: nfs-storage
          mountPath: "/data"
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc