{
 "title": "Netology",
 "time": { "from": "2025-04-12T18:52:16.999Z", "to": "2025-04-13T17:06:19.463Z" },
 "panels": [
  {
   "title": "CPU Load Average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Free Memory (MB)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024  # в МБ"
    }
   ]
  },
  {
   "title": "Free Disk Space (GB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    }
   ]
  }
 ]
}